# Generated by Django 2.0.6 on 2018-06-05 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bbs', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='categrate',
            new_name='category',
        ),
    ]
